# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Review_App', '0004_auto_20170223_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author_book', to='Review_App.Author'),
            preserve_default=False,
        ),
    ]
