# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='course',
            new_name='courses',
        ),
    ]
