# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170222_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseRegister', to='Course_App.Courses'),
        ),
    ]
